# Generated by Django 4.2.15 on 2024-08-27 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(db_column='product', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.product'),
        ),
    ]
